# ヘッダーナビゲーションメニュー
[[menu.main]]
name = "トップ"
url = "/"
weight = 10

[[menu.main]]
name = "山行記録"
url = "/categories/山行記録/"
weight = 20

[[menu.main]]
name = "カンツォーネ"
url = "/categories/カンツォーネ/"
weight = 30

[[menu.main]]
name = "雑感"
url = "/categories/雑感/"
weight = 40

[[menu.main]]
name = "プロフィール"
url = "/profile/"
weight = 50

[[menu.main]]
name = "タグ"
url = "/tags/"
weight = 60

[[menu.main]]
name = "アーカイブ"
url = "/archives/"
weight = 70

[[menu.main]]
name = "検索"
url = "/search/"
weight = 80

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardLineBreaks = false